name: Push to USB
on:
  push:
    branches:
      - dev
jobs:
  push-to-usb:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Sync changed repository Python to USB
        run: |
          rsync -a --include="*/" --include="*.py" --exclude="*" --update $GITHUB_WORKSPACE/ /Volumes/CIRCUITPY
